### PR TITLE
issue #41: backport the pure python suggestion code from 3.12

### PR DESCRIPTION
**Pull request by cfbolz**
First attempt. Code is from here: https://github.com/python/cpython/commit/bbc7cd649a6ef56eb09278f3e746ca89b9d592c9

I suppose a few more tests would be good?

### CODE REVIEW

**Comment by agronholm** [comment]
> I suppose a few more tests would be good?

Passing tests would be good :)

**Comment by cfbolz** [comment]
That too ;-)

**Comment by cfbolz** [comment]
of course it passes locally on 3.10 and pypy, otherwise I wouldn't have pushed. how do you usually run tests locally?

**Comment by agronholm** [comment]
> of course it passes locally on 3.10 and pypy, otherwise I wouldn't have pushed. how do you usually run tests locally?

I usually just run `tox -p` before pushing.

**Comment by cfbolz** [comment]
so 3.11 fails, because there `exceptiongroup.format_exception` etc just defer to the `traceback` module, which does not do suggestions in 3.11 yet. I could 1) skip the test there or 2) change the logic in `__init__.py` to use 3.12 as the cutoff, because `traceback.py` *will* have suggestion support there.

**Comment by agronholm** [comment]
I'm a bit confused; the test suite should not be calling `exceptiongroup.format_exception()` at all on Python 3.11. Instead it should be calling `traceback.format_exception()`. Since nothing is being patched on 3.11, it should "just work", yes?

**Comment by agronholm** [comment]
Ok so, let me change the question. With `exceptiongroup` not patching anything on 3.11, it also won't break anything, right? If that is so, then skipping the test on 3.11 seems like the right thing to do.

**Comment by cfbolz** [comment]
> With exceptiongroup not patching anything on 3.11, it also won't break anything, right? If that is so, then skipping the test on 3.11 seems like the right thing to do.

Yes, that reasoning makes a lot of sense, I just did that.

**Comment by agronholm** [comment]
Goodie! Anything missing from the PR? I see it's still marked as draft.

**Comment by agronholm** [comment]
Thanks!

**Comment by cfbolz** [comment]
awesome, thank you!

**Comment by jdavies-st** [comment]
So currently in Python 3.11.0, the suggestions for `NameError` and `AttributeError` still seem to be computed on-the-fly and are not a part of the traceback.  An example:

```python
>>> class Foo:
...     def _bar(self):
...         return 42
... 
>>> foo = Foo()
>>> foo.bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Foo' object has no attribute 'bar'. Did you mean: '_bar'?
>>> try:
...     foo.bar
... except AttributeError as e:
...     print(e)
... 
'Foo' object has no attribute 'bar'
```

Is this supposed to change during some patch release of 3.11.x?

**Comment by jdavies-st** [comment]
Thanks.  Then perhaps the issue we are seeing in astropy/astropy#14005 is actually an upstream usage of `exceptiongroup` by `pytest`.  In terms of `NameError` and `AttributeError` suggestions, Python 3.10 and 3.11 should be treated the same, but now 3.10 is being patched (to work like 3.12), but 3.11 is not.

**Pull request merged**
