### PR TITLE
PEP 678: new API for add_note()

### PR DESCRIPTION
**Pull request by Zac-HD**
Just after my last PR - and after we'd asked the Steering Council to consider the PEP - we had some translation-related concerns that ended up prompting a slight redesign.  So here's another PR with the new interface!

(and I'm sorry for the churn!  Thanks for maintaining the backport 💖)

### CODE REVIEW

**Review by agronholm — CHANGES_REQUESTED** [review]
Add a changelog entry and we're good.

I take it that the py3.11 tests will start working with the next alpha release?

**Comment by Zac-HD** [comment]
> I take it that the py3.11 tests will start working with the next alpha release?

Yep, should do. If you want to hold off on merging until then that's fine by me.

**Comment by agronholm** [comment]
If you compile the latest version from `main` and run the test suite on that and it passes, I'll agree to merge this.

**Comment by Zac-HD** [comment]
PEP-678 has formally been accepted (🥳), and I've updated this PR accordingly with the final design.

Once https://github.com/python/cpython/pull/31317 is merged upstream, I'll confirm that the 3.11 tests pass on CPython `main`, and then we'll be all set for 3.11.0b1 in early May.

**Comment by agronholm** [comment]
Have you confirmed that this PR passes against CPython 3.11 main? If so, then I'll merge.

**Comment by Zac-HD** [comment]
It seems to work, though I wanted to confirm that everything plays well together over the weekend before asking you to merge and release - apologies for the delay, but I was asked to present a tutorial at PyCon next week and that's been a fairly urgent call on my OSS time.

**Comment by Zac-HD** [comment]
@agronholm - I've retested everything against CPython nightly locally, and it's ready to merge 🚀 

Thanks again for your patience!

**Comment by agronholm** [comment]
Thanks!

**Comment by Zac-HD** [comment]
Nice! Ping me when you release on PyPI?

**Comment by Zac-HD** [comment]
Awesome!

**Pull request merged**
